### PR TITLE
Function names are updated and made meaningful.

### PR DESCRIPTION
**Pull request by rishabh-327**

### CODE REVIEW

**Comment by kimberlythegeek** [comment]
thanks @rishabh-327 ! The updated axe-selenium-python package that this depends on has not been uploaded to PyPi. I will do that now, and then bumping the version number should fix the build.

**Comment by m8ttyB** [comment]
@kimberlythegeek what's the status of axe-selenium-python and PyPi? Can @rishabh-327's pr be merged?

**Comment by rishabh-327** [comment]
Seems like updated axe-selenium-python package with changed method names has not been uploaded to PyPi.

**Comment by kimberlythegeek** [comment]
Hi @rishabh-327 – apologies for the delay.

The most recent changes have been uploaded to PyPi. The tests are likely failing because the requirements file has not been updated.

Try setting `axe_selenium_python==2.1.5` in  `pytest_axe/test/requirements/tests.txt` and pushing those commits. I'll keep an eye on the build

**Comment by kimberlythegeek** [comment]
one last place to update method name:

https://github.com/mozilla-services/pytest-axe/blob/b9e22c028420abeb0b920e33d3a2debb9274e627/pytest_axe/tests/test_axe.py#L30

try running the tests locally using `tox` before pushing your commits.

**Comment by m8ttyB** [comment]
To echo what @kimberlythegeek has said, @rishabh-327 thank you for all of your work. If you have questions or simply want to say hello, [stop into irc](https://wiki.mozilla.org/IRC), `#fx-test` channel and say hello if you're not already online.

**Comment by rishabh-327** [comment]
> one last place to update method name:
> 
> [pytest-axe/pytest_axe/tests/test_axe.py](https://github.com/mozilla-services/pytest-axe/blob/b9e22c028420abeb0b920e33d3a2debb9274e627/pytest_axe/tests/test_axe.py#L30)
> 
> Line 30 in [b9e22c0](/mozilla-services/pytest-axe/commit/b9e22c028420abeb0b920e33d3a2debb9274e627)
> 
>  violations = test_page_with_violations.run() 
> try running the tests locally using `tox` before pushing your commits.

Done with fixing that, but I'm facing trouble trying to run the test locally using tox.

**Comment by kimberlythegeek** [comment]
Thanks!

**Pull request merged**
